name: Deploy (stable -> wit-anchor-dev)

on:
  push:
    branches:
      - stable

permissions:
  contents: read
  checks: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ★ここが肝：サービスアカウントJSONを使ってHostingにデプロイ
      - name: Deploy to Firebase Hosting (wit-anchor-dev)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WIT_ANCHOR }}
          projectId: wit-anchor
          # target を使っている場合だけ有効（firebase.json の "hosting": { "target": ... } と一致させる）
          target: wit-anchor-dev
          # live に出す（プレビュー運用したいなら channelId を preview 等に変える）
          channelId: live
