# ------------------------------------------------------------
# APP: wit-anchor / Firebase Hosting Deploy (GitHub Actions)
# FILE: .github/workflows/firebase-hosting.yml
# VERSION: v1.0.0
# DATE(JST): 2026-01-05 18:46 JST
# TITLE: Service Account JSON を GITHUB Secret から書き出して Hosting deploy
# CHANGES:
# - SecretのJSONを printf でそのまま key.json に保存（改行崩れ対策）
# - GOOGLE_APPLICATION_CREDENTIALS を明示して firebase deploy
# AUTHOR: Yui
# ------------------------------------------------------------

name: Deploy (stable -> Firebase Hosting)

on:
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      - name: Write service account key (JSON)
        shell: bash
        run: |
          mkdir -p "$HOME/.firebase"
          # Secretに入っているJSONを「そのまま」ファイル化（echoより安全）
          printf '%s' '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WIT_ANCHOR }}' > "$HOME/.firebase/key.json"
          # 念のためファイル存在だけ確認（中身は出さない）
          test -s "$HOME/.firebase/key.json"

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-key.json
        shell: bash
        run: |
          # runner.temp に置く（権限/パスの癖を避ける）
          cp "$HOME/.firebase/key.json" "${{ runner.temp }}/firebase-key.json"
          firebase --version
          firebase deploy --only hosting --project wit-anchor --non-interactive
