name: Deploy (stable -> wit-anchor-dev)

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write service account key
        run: |
          mkdir -p $HOME/.firebase
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WIT_ANCHOR }}' > $HOME/.firebase/service-account.json

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/.firebase/service-account.json
        run: |
          firebase deploy \
            --only hosting \
            --project wit-anchor \
            --non-interactive
